version: "3.8"
services:
  ubu:
    image: image1
    container_name: c1
    ports:
    - "8017:80"
    volumes:
    - vlm:/data
    networks:
    - net1

volumes:
  vlm:
networks:
  net1:
    driver: bridge
